version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  processor:
    build: ./processor
    depends_on:
      - rabbitmq
    volumes:
      - shared_data:/data

  collector:
    build: ./collector
    depends_on:
      - rabbitmq
    volumes:
      - shared_data:/data

  recommender:
    build: ./recommender
    volumes:
      - shared_data:/data

volumes:
  shared_data:
